CREATE TABLE ConfigurationProperty (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	key varchar(255) not null,
	value varchar(255) not null
);

insert into ConfigurationProperty (key, value) values ('autoSalesRep', '920274');
