-- CREATE TABLE configuration_property (
-- 	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
-- 	key varchar(255) not null,
-- 	value varchar(255) not null
-- );

insert into configuration_property (key, value) values ('autoSalesRep', '920274');
